services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - docker
    env_file:
      - .env

  postgres:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - docker
    env_file:
      - .env

networks:
  docker:
    driver: bridge

volumes:
  pgdb:
    driver: local
