services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - docker

  postgres:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - docker

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - docker
    depends_on:
      - backend

networks:
  docker:
    driver: bridge
